#Resource Icon, 1, "folder_explore.ico"

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Check a disk's free space"
#Resource Version$ "LegalCopyright",   "Copyright 2013, 2016 BasicAware"
#Resource Version$ "OriginalFilename", "CheckDiskFree.exe"
#Resource Version$ "ProductName",      "CheckDiskFree"
#Resource Version$ "ProductVersion",   "1.0.0.0"
#Resource Version$ "FileVersion",      "1.0.0.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
