#Resource Icon, 1, "folder_explore.ico"
#Resource Manifest 1, "CheckDiskFree.exe.manifest"

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Query free disk space"
#Resource Version$ "LegalCopyright",   "Copyright 2012-2018 BasicAware"
#Resource Version$ "OriginalFilename", "CheckDiskFree.exe"
#Resource Version$ "ProductName",      "CheckDiskFree"
#Resource Version$ "ProductVersion",   "1.0.3.0"
#Resource Version$ "FileVersion",      "1.0.3.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
